### ISSUE TITLE
Need a method to validate polylines

### ISSUE THREAD

**Issue by robrwo** [spurkis/Geo-Google-PolylineEncoder#1]
The decode method blindly tries to decode anything, and just emits warnings like "substr outside of string" and "Use of uninitialized value in ord". 

If nothing else, it should have a method that checks if a polyline is well-formed (as characters in the appropriate range and is not missing anything).

**Comment by spurkis** [comment]
Hi Robert,

That sounds like a good idea - want to give it a shot?  I'm happy to give you commit access & co-maint on CPAN.

Cheers,
-Steve

**Comment by robrwo** [comment]
Ok. My CPAN id is RRWO.

**Comment by spurkis** [comment]
Great - I've added you to the list of collaborators on github, and you are now a co-maintainer on CPAN:

  "Added RRWO to co-maintainers of Geo::Google::PolylineEncoder."

Cheers,
-Steve

**Comment by robrwo** [comment]
See the validation branch.

**Comment by robrwo** [comment]
Merged into master
